Repository superdesk/superdesk-planning, pull requests merged in 2025-06, with the labels that each got.

#2339 [SDESK-7497] Fix Event Cancel & Reschedule endpoints
  server/features/environment.py
  server/features/events_cancel.feature
  server/features/events_reschedule.feature
  server/planning/common.py
  server/planning/events/__init__.py
  server/planning/events/events.py
  server/planning/events/events_cancel.py
  server/planning/events/events_reschedule.py
  server/planning/events/events_tests.py
  server/planning/events/events_utils.py
  server/planning/events/views.py
  server/planning/signals.py
  server/planning/tests/output_formatters/file_providers_test.py
  server/requirements.txt
Labels: async

#2343 [SDESK-7497] Fix remaining behave tests
  server/features/assignments_link.feature
  server/features/assignments_revert.feature
  server/features/content_rewrite.feature
  server/features/environment.py
  server/features/planning.feature
  server/features/planning_cancel.feature
  server/features/planning_featured_post.feature
  server/features/planning_recurring.feature
  server/features/planning_validate.feature
  server/features/publish.feature
  server/features/search_combined.feature
  server/features/search_events.feature
  server/features/search_planning.feature
  server/features/steps/steps.py
  server/planning/assignments/assignments.py
  server/planning/assignments/assignments_complete.py
  server/planning/assignments/assignments_revert.py
  server/planning/events/events_post.py
  server/planning/planning/planning_duplicate.py
  server/planning/planning/planning_featured_async_service.py
  server/planning/planning/planning_spike.py
  server/planning/planning/views.py
  server/planning/planning_notifications.py
  server/planning/search/planning_search.py
  server/planning/types/planning_featured.py
Labels: async

#2367 [SDESK-7675] - Event freezes and gets locked when saving after adding a related planning
  client/reducers/locks.ts
Labels: bug

#2371 [STT-1238] fix: Publish Planning to ContentAPI fails when linked to an Event
  server/planning/content_api/types/planning.py
  server/planning/types/__init__.py
Labels: async

#2370 [SDESK-7676] - Featured stories error when viewing planning items with related events
  client/utils/planning.tsx
Labels: bug, async
